server:
  port: 8080

topic-name:
  string: string-topic
  json: json-topic

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/kafka
    username: root
    password: MySQL@123
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  application:
    name: spring-boot-apache-kafka
  kafka:
    consumer:
      bootstrap-servers: localhost:9092
      group-id: group_id
    producer:
      bootstrap-servers: localhost:9092